### ISSUE TITLE
Constrain macro

### ISSUE THREAD

**Issue by bask185** [ramdeoshubham/macros#4]
The arduino library has a constrain macro which I find quite useful. Perhaps a nice addition?

`#define constrain(amt,low,high) ((amt)<(low)?(low):((amt)>(high)?(high):(amt)))`

**Comment by ramdeoshubham** [comment]
Of course !
Can you make a pull request in the macros.h at the end of the file, so that we can acknowledge you as a contributor 😄 ?
Thanks !

**Comment by ramdeoshubham** [comment]
Ohkay I added it myself. Thanks for your suggestion.
https://github.com/ramdeoshubham/macros/commit/d402c30e27f129eb3db1f8cde33331686ce1165d
